"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SDK_VERSION = void 0;
/** AUTO-GENERATED by scripts/sync-sdk-version.mjs — do not edit. */
exports.SDK_VERSION = '0.1.0';
